### ISSUE TITLE
Dollar sign problem

### ISSUE THREAD

**Issue by jackchatelain** [phatblat/MyFortuneCookie#1]
The "Someone will give you 10$" Fortune has the $ on the wrong side of the 10.

**Comment by phatblat** [comment]
This is an easy fix. If you want you can modify [Fortunes.plist](https://github.com/phatblat/MyFortuneCookie/blob/master/MyFortuneCookie/Fortunes.plist#L15) using the GitHub web editor and then I can create a new build of the app.
